#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: github-auth-overlay
  annotations:
    tekton.dev/git-0: #@ data.values.imported.git.host 
type: kubernetes.io/basic-auth
stringData:
  github-auth-overlay.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@ def customize():
    #@overlay/match by=overlay.subset({"apiVersion": "v1", "kind": "ServiceAccount"}), expects="0+"
    ---
    secrets:
      #@overlay/append
      - name: github-auth
    #@  end