---
apiVersion: v1
kind: ConfigMap
metadata:
  name: desired-namespaces
  namespace: tap-namespace-provisioning
  annotations:
    kapp.k14s.io/create-strategy: fallback-on-update
data:
  namespaces.yaml: |
    #@data/values
    ---
    namespaces:
    - name: dev
      scanpolicy: lax
      pipeline: java
      limits:
        default:
          cpu: 1200m
          memory: 1.5Gi
        defaultRequest:
          cpu: 300m
          memory: 30Mi
    - name: qa
      scanpolicy: strict
      pipeline: java